// Ticket Web application/react-js/src/components/auth/Register.js
import React, { useState, useEffect } from "react"
import { useDispatch, useSelector } from "react-redux"
import { Formik, Field, Form, ErrorMessage } from "formik"
import * as Yup from "yup"

import { register } from "../auth/authSlice"
import { clearMessage } from "../message/messageSlice"

const Register = () => {
	const [successful, setSuccessful] = useState(false)

	const { message } = useSelector((state) => state.message)
	const dispatch = useDispatch()

	useEffect(() => {
		dispatch(clearMessage())
	}, [dispatch])

	const initialValues = {
		username: "",
		email: "",
		password: "",
	}

	const validationSchema = Yup.object().shape({
		username: Yup.string()
			.test("len", "The username must be between 3 and 20 characters.", (val) => val && val.toString().length >= 3 && val.toString().length <= 20)
			.required("This field is required!"),
		email: Yup.string().email("This is not a valid email.").required("This field is required!"),
		password: Yup.string()
			.test("len", "the password len is 4 to 40", (val) => val && val.toString().length >= 6 && val.toString().length <= 40)
			.test("regex", "The password should contains a number.", (val) => new RegExp("^(?=.*[a-z])(?=.*[0-9])(?=.{8,})").test(val))
			.required("This field is required!"),
	})

	const handleRegister = (formValue) => {
		const { username, email, password } = formValue

		setSuccessful(false)

		dispatch(register({ username, email, password }))
			.unwrap()
			.then(() => {
				setSuccessful(true)
			})
			.catch((error) => {
				setSuccessful(false)
			})
	}

	return (
		<div className="col-md-12 signup-form">
			<div className="card card-container">
				<img src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" alt="profile-img" className="profile-img-card" />
				<Formik initialValues={initialValues} validationSchema={validationSchema} onSubmit={handleRegister}>
					<Form>
						{!successful && (
							<div>
								<div className="form-group">
									<label htmlFor="email">Email</label>
									<Field name="email" type="email" className="form-control" />
									<ErrorMessage name="email" htmlFor="email" component="div" className="alert alert-danger" />
								</div>
								<div className="form-group">
									<label htmlFor="username">Username</label>
									<Field name="username" type="text" className="form-control" />
									<ErrorMessage name="username" htmlFor="username" component="div" className="alert alert-danger" />
								</div>

								<div className="form-group">
									<label htmlFor="password">Password</label>
									<Field name="password" type="password" htmlFor="password" className="form-control" />
									<ErrorMessage name="password" component="div" className="alert alert-danger" />
								</div>

								<div className="form-group">
									<button type="submit" className="btn btn-primary btn-block">
										Sign Up
									</button>
								</div>
							</div>
						)}
					</Form>
				</Formik>
			</div>

			{message && (
				<div className="form-group">
					<div className={successful ? "alert alert-success" : "alert alert-danger"} role="alert">
						{message}
					</div>
				</div>
			)}
		</div>
	)
}

export default Register

// Ticket Web application/angular/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../_services/auth.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent implements OnInit {
  form: any = {
    username: null,
    email: null,
    password: null,
  };
  isSuccessful = false;
  isSignUpFailed = false;
  errorMessage = '';

  constructor(private authService: AuthService) { }

  ngOnInit(): void { }

  onSubmit(): void {
    const { username, email, password } = this.form;

    this.authService.register(username, email, password).subscribe({
      next: (data) => {
        console.log(data);
        this.isSuccessful = true;
        this.isSignUpFailed = false;
      },
      error: (err) => {
        console.log(err);
        this.errorMessage = err.error.firstError;
        this.isSignUpFailed = true;
      },
    });
  }
}

<div class="col-md-12">
  <div class="card card-container">
    <img
      id="profile-img"
      src="//ssl.gstatic.com/accounts/ui/avatar_2x.png"
      class="profile-img-card"
    />
    <form
      *ngIf="!isSuccessful"
      name="form"
      (ngSubmit)="f.form.valid && onSubmit()"
      #f="ngForm"
      novalidate
    >
      <div class="form-group">
        <label for="username">Username</label>
        <input
          type="text"
          class="form-control"
          name="username"
          [(ngModel)]="form.username"
          required
          minlength="3"
          maxlength="20"
          #username="ngModel"
        />
        <div class="alert-danger" *ngIf="username.errors && f.submitted">
          <div *ngIf="username.errors['required']">Username is required</div>
          <div *ngIf="username.errors['minlength']">
            Username must be at least 3 characters
          </div>
          <div *ngIf="username.errors['maxlength']">
            Username must be at most 20 characters
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="email"
          class="form-control"
          name="email"
          [(ngModel)]="form.email"
          required
          email
          #email="ngModel"
        />
        <div class="alert-danger" *ngIf="email.errors && f.submitted">
          <div *ngIf="email.errors['required']">Email is required</div>
          <div *ngIf="email.errors['email']">
            Email must be a valid email address
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          name="password"
          [(ngModel)]="form.password"
          required
          minlength="6"
          #password="ngModel"
        />
        <div class="alert-danger" *ngIf="password.errors && f.submitted">
          <div *ngIf="password.errors['required']">Password is required</div>
          <div *ngIf="password.errors['minlength']">
            Password must be at least 6 characters
          </div>
        </div>
      </div>
      <div class="form-group">
        <button class="btn btn-primary btn-block">Sign Up</button>
      </div>

      <div class="alert alert-warning" *ngIf="f.submitted && isSignUpFailed">
        Signup failed!<br />{{ errorMessage }}
      </div>
    </form>

    <div class="alert alert-success" *ngIf="isSuccessful">
      Your registration is successful! Please go to <a href="/login">Login Page</a>
    </div>
  </div>
</div>
