// Ticket Web application/angular/src/app/login/login.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AuthService } from '../_services/auth.service';
import { TokenStorageService } from '../_services/token-storage.service';
import { Router } from '@angular/router';
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  form: any = {
    email: null,
    password: null,
  };
  isLoginFailed = false;
  errorMessage = '';

  constructor(
    readonly authService: AuthService,
    private tokenStorage: TokenStorageService,
    private router: Router
  ) {}

  ngOnInit(): void {
    if (this.tokenStorage.getToken()) {
      this.authService.isLoggedIn = true;
    }
  }

  onSubmit(): void {
    const { email, password } = this.form;
    this.authService.login(email, password).subscribe({
      next: (data) => {
        this.tokenStorage.saveToken(data.data.accessToken);
        this.tokenStorage.saveUser(data.data);

        this.isLoginFailed = false;
        this.authService.isLoggedIn = true;

        this.router.navigate(['/profile']);
      },
      error: (err) => {
        this.errorMessage = err.error.error.message;
        this.isLoginFailed = true;
      },
    });
  }
}

<div class="col-md-12">
  <div class="card card-container">
    <img id="profile-img" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" class="profile-img-card" />
    <form *ngIf="!this.authService.isLoggedIn" name="form" (ngSubmit)="f.form.valid && onSubmit()" #f="ngForm" novalidate>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" name="email" [(ngModel)]="form.email" required #email="ngModel" />
        <div class="alert alert-danger" role="alert" *ngIf="email.errors && f.submitted">
          email is required!
        </div>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" [(ngModel)]="form.password" required minlength="6"
          #password="ngModel" />
        <div class="alert alert-danger" role="alert" *ngIf="password.errors && f.submitted">
          <div *ngIf="password.errors['required']">Password is required</div>
          <div *ngIf="password.errors['minlength']">
            Password must be at least 6 characters
          </div>
        </div>
      </div>
      <div class="form-group">
        <button class="btn btn-primary btn-block">Login</button>
      </div>
      <div class="form-group">
        <div class="alert alert-danger" role="alert" *ngIf="f.submitted && isLoginFailed">
          Login failed: {{ errorMessage }}
        </div>
      </div>
    </form>
  </div>
</div>

// Ticket Web application/react-js/src/components/auth/Login.js
import React, { useState, useEffect } from "react"
import { useDispatch, useSelector } from "react-redux"
import { Navigate } from "react-router-dom"
import { Formik, Field, Form, ErrorMessage } from "formik"
import * as Yup from "yup"
import "./login.css"
import { login_fulfilled, login_rejected } from "../slice/authSlice"
import { login } from "../slice/authSlice"

const Login = (props) => {
	const [loading, setLoading] = useState(false)
	const [message, setMessage] = useState("")
	const { isLoggedIn } = useSelector((state) => state.auth)
	const dispatch = useDispatch()


	useEffect(() => {
		if (isLoggedIn) {
			return <Navigate to="/" />
		}
	}, [isLoggedIn])

	const initialValues = {
		email: "",
		password: "",
	}

	const validationSchema = Yup.object().shape({
		email: Yup.string().required("This field is required!"),
		password: Yup.string().required("This field is required!"),
	})

	const handleLogin = (formValue) => {
		const { email, password } = formValue
		setLoading(true)

		dispatch(login({ email, password }))
			.unwrap()
			.then((data) => {
				if (data.error) {
					setMessage(data.error)
					setLoading(false)
					return dispatch(login_rejected(data.error))
				}
				dispatch(login_fulfilled(data.data))
				// navigate("/")
				props.history.push("/")
			})
			.catch((error) => {
				dispatch(login_rejected())
				setLoading(false)
				setMessage(error.message)
			})
	}

	if (isLoggedIn) {
		return <Navigate to="/" />
	}

	return (
		<div className="col-md-12 login-form">
			<div className="card card-container">
				<img
					src="//ssl.gstatic.com/accounts/ui/avatar_2x.png"
					alt="profile-img"
					className="profile-img-card"
				/>
				<Formik
					initialValues={initialValues}
					validationSchema={validationSchema}
					onSubmit={handleLogin}
				>
					<Form>
						<div className="form-group">
							<label htmlFor="email">Email</label>
							<Field
								name="email"
								type="text"
								className="form-control"
							/>
							<ErrorMessage
								name="email"
								component="div"
								className="alert alert-danger"
							/>
						</div>

						<div className="form-group">
							<label htmlFor="password">Password</label>
							<Field
								name="password"
								type="password"
								className="form-control"
							/>
							<ErrorMessage
								name="password"
								component="div"
								className="alert alert-danger"
							/>
						</div>

						<div className="form-group">
							<button
								type="submit"
								className="btn btn-primary btn-block"
								disabled={loading}
							>
								{loading && (
									<span className="spinner-border spinner-border-sm"></span>
								)}
								<span>Login</span>
							</button>
						</div>
					</Form>
				</Formik>
			</div>

			{message && (
				<div className="form-group">
					<div className="alert alert-danger" role="alert">
						{message}
					</div>
				</div>
			)}
		</div>
	)
}

export default Login
